name: App Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  trigger-central-pipeline:
    uses: ShahmeerKhan137/DevOps-Platform/.github/workflows/smart-ci.yml@main
    with:
      enable_checkout: true
      enable_detection: true
      enable_build: true
      enable_publish: true
    permissions:
      contents: read
      packages: write